#include "nrf_bsp.h"

extern uint16_t m_conn_handle;

/**@brief Function for handling events from the BSP module.
 *
 * @param[in]   event   Event generated by button press.
 */
static void bsp_event_handler(bsp_event_t event)
{
	ret_code_t err_code;

	switch (event)
	{
	case BSP_EVENT_SLEEP:
		NRF_Util.sleep_mode_enter();
		break;

	case BSP_EVENT_DISCONNECT:
		err_code = sd_ble_gap_disconnect(m_conn_handle,
			BLE_HCI_REMOTE_USER_TERMINATED_CONNECTION);
		if (err_code != NRF_ERROR_INVALID_STATE)
		{
			APP_ERROR_CHECK(err_code);
		}
		break;

	case BSP_EVENT_WHITELIST_OFF:
		if (m_conn_handle == BLE_CONN_HANDLE_INVALID)
		{
			err_code = ble_advertising_restart_without_whitelist(&m_advertising);
			if (err_code != NRF_ERROR_INVALID_STATE)
			{
				APP_ERROR_CHECK(err_code);
			}
		}
		break;

	case BSP_EVENT_KEY_0:
		if (m_conn_handle != BLE_CONN_HANDLE_INVALID)
		{
			NRF_Services.mouse_movement_send(-MOVEMENT_SPEED, 0);
		}
		break;

	case BSP_EVENT_KEY_1:
		if (m_conn_handle != BLE_CONN_HANDLE_INVALID)
		{
			NRF_Services.mouse_movement_send(0, -MOVEMENT_SPEED);
		}
		break;

	case BSP_EVENT_KEY_2:
		if (m_conn_handle != BLE_CONN_HANDLE_INVALID)
		{
			NRF_Services.mouse_movement_send(MOVEMENT_SPEED, 0);
		}
		break;

	case BSP_EVENT_KEY_3:
		if (m_conn_handle != BLE_CONN_HANDLE_INVALID)
		{
			NRF_Services.mouse_movement_send(0, MOVEMENT_SPEED);
		}
		break;

	default:
		break;
	}
}

/**@brief Function for initializing buttons and leds.
 *
 * @param[out] p_erase_bonds  Will be true if the clear bonding button was pressed to wake the application up.
 */
static void buttons_leds_init(bool * p_erase_bonds)
{
	ret_code_t err_code;
	bsp_event_t startup_event;

	err_code = bsp_init(BSP_INIT_LEDS | BSP_INIT_BUTTONS, bsp_event_handler);

	APP_ERROR_CHECK(err_code);

	err_code = bsp_btn_ble_init(NULL, &startup_event);
	APP_ERROR_CHECK(err_code);

	*p_erase_bonds = (startup_event == BSP_EVENT_CLEAR_BONDING_DATA);
}

const struct nrf_bsp NRF_Bsp = { 
	.buttons_leds_init = buttons_leds_init,
	
};
